name: ftp
description: "Simple ftp client"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  auto_route: ^10.0.1
  ftpconnect: ^2.0.7

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  dart_code_linter: ^2.0.0
  flutter_gen: ^5.10.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer_plugin: ^0.12.0
  analyzer: ^7.0.0